import { prisma } from '../lib/prisma'
import logger from '../lib/logger'
import crypto from 'crypto'

/**
 * 字幕服务
 * 从剧本/配音生成时间轴字幕，支持 SRT/VTT/ASS 导出
 */

interface SubtitleEntry {
  id: number
  start_time: number
  end_time: number
  text: string
  speaker?: string
}

/**
 * @description 从 Shot 列表自动生成字幕（快速模式：基于文本+音频时长分配）
 */
export async function generateSubtitlesFromShots(episode_id: string, project_id: string) {
  const shots = await prisma.shot.findMany({
    where: { episode_id, project_id },
    include: { Character: true },
    orderBy: [{ episode_number: 'asc' }, { segment_id: 'asc' }, { cell_id: 'asc' }],
  })

  const entries: SubtitleEntry[] = []
  let currentTime = 0
  let entryId = 1

  for (const shot of shots) {
    const text = shot.subtitle_text || ''
    if (!text.trim()) {
      currentTime += (shot.audio_duration || shot.duration * 1000)
      continue
    }

    const duration = shot.audio_duration || estimateDuration(text)
    entries.push({
      id: entryId++,
      start_time: currentTime,
      end_time: currentTime + duration,
      text: text.trim(),
      speaker: shot.Character?.name,
    })

    currentTime += duration + 200
  }

  const now = new Date()
  const existing = await prisma.subtitle.findFirst({
    where: { episode_id, project_id },
  })

  if (existing) {
    const updated = await prisma.subtitle.update({
      where: { id: existing.id },
      data: { entries: entries as any, updated_at: now },
    })
    logger.info('字幕已更新', { episode_id, entry_count: entries.length })
    return updated
  }

  const subtitle = await prisma.subtitle.create({
    data: {
      id: crypto.randomUUID(),
      project_id,
      episode_id,
      entries: entries as any,
      format: 'srt',
      language: 'zh-CN',
      created_at: now,
      updated_at: now,
    },
  })

  logger.info('字幕已生成', { episode_id, entry_count: entries.length })
  return subtitle
}

/**
 * @description 获取一集的字幕
 */
export async function getSubtitle(episode_id: string, project_id: string) {
  return prisma.subtitle.findFirst({ where: { episode_id, project_id } })
}

/**
 * @description 更新字幕条目
 */
export async function updateSubtitleEntries(subtitle_id: string, entries: SubtitleEntry[]) {
  return prisma.subtitle.update({
    where: { id: subtitle_id },
    data: { entries: entries as any, updated_at: new Date() },
  })
}

/**
 * @description 更新字幕样式
 */
export async function updateSubtitleStyle(subtitle_id: string, style: Record<string, any>) {
  return prisma.subtitle.update({
    where: { id: subtitle_id },
    data: { style: style as any, updated_at: new Date() },
  })
}

/**
 * @description 导出为 SRT 格式
 */
export function exportToSRT(entries: SubtitleEntry[]): string {
  return entries.map(entry => {
    const start = formatSRTTime(entry.start_time)
    const end = formatSRTTime(entry.end_time)
    return `${entry.id}\n${start} --> ${end}\n${entry.text}\n`
  }).join('\n')
}

/**
 * @description 导出为 VTT 格式
 */
export function exportToVTT(entries: SubtitleEntry[]): string {
  const header = 'WEBVTT\n\n'
  const body = entries.map(entry => {
    const start = formatVTTTime(entry.start_time)
    const end = formatVTTTime(entry.end_time)
    return `${start} --> ${end}\n${entry.text}\n`
  }).join('\n')
  return header + body
}

/**
 * @description 导出为 ASS/SSA 格式
 * 说明：这里使用一个默认样式（不读取 style 配置面板），只保证时间轴与文本正确输出。
 */
export function exportToASS(entries: SubtitleEntry[]): string {
  const header = `[Script Info]
; Generated by KaiyanTool
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: 1080
PlayResY: 1920

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`

  const body = entries
    .map(entry => {
      const start = formatASSDialogueTime(entry.start_time)
      const end = formatASSDialogueTime(entry.end_time)
      // ASS 文本中换行用 \N；去掉可能影响解析的大括号标签
      const text = entry.text
        .replace(/\r\n|\r|\n/g, '\\N')
        .replace(/[{}]/g, '')
      return `Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`
    })
    .join('\n')

  return header + body + '\n'
}

function estimateDuration(text: string): number {
  return Math.max(1000, text.length * 200)
}

function formatSRTTime(ms: number): string {
  const hours = Math.floor(ms / 3600000)
  const minutes = Math.floor((ms % 3600000) / 60000)
  const seconds = Math.floor((ms % 60000) / 1000)
  const millis = ms % 1000
  return `${pad(hours)}:${pad(minutes)}:${pad(seconds)},${pad3(millis)}`
}

function formatVTTTime(ms: number): string {
  const hours = Math.floor(ms / 3600000)
  const minutes = Math.floor((ms % 3600000) / 60000)
  const seconds = Math.floor((ms % 60000) / 1000)
  const millis = ms % 1000
  return `${pad(hours)}:${pad(minutes)}:${pad(seconds)}.${pad3(millis)}`
}

function formatASSDialogueTime(ms: number): string {
  const hours = Math.floor(ms / 3600000)
  const minutes = Math.floor((ms % 3600000) / 60000)
  const seconds = Math.floor((ms % 60000) / 1000)
  const centiseconds = Math.floor((ms % 1000) / 10)
  // ASS 时间格式：H:MM:SS.CC
  return `${hours}:${pad(minutes)}:${pad(seconds)}.${pad(centiseconds)}`
}

function pad(n: number): string {
  return n.toString().padStart(2, '0')
}

function pad3(n: number): string {
  return n.toString().padStart(3, '0')
}
