import React, { useState, useEffect } from 'react';
import {
  X,
  Sparkles,
  Users,
  Package,
  MapPin,
  Loader2,
  Check,
  AlertCircle,
  ArrowRight,
  Palette,
} from 'lucide-react';
import { Button } from '../../components/ui/button-new';
import { ModelSelector } from '../../components/ui/ModelSelector/ModelSelector';

interface AutoGenerateDialogProps {
  isOpen: boolean;
  onClose: () => void;
  characters: { name: string; description: string }[];
  scenes: string[];
  props?: { name: string; description: string }[];
  onGenerate: (model: string, style: string) => Promise<void>;
  isGenerating: boolean;
  progress: { current: number; total: number; status: string };
}

const STYLE_OPTIONS = [
  { id: 'cinematic', name: '电影质感', icon: '🎬' },
  { id: 'anime', name: '动漫风格', icon: '🎨' },
  { id: 'realistic', name: '写实风格', icon: '📷' },
  { id: 'q_version_blind_box', name: 'Q版盲盒', icon: '🎁' },
  { id: 'disney_pixar', name: '皮克斯动画', icon: '✨' },
  { id: 'cyberpunk', name: '赛博朋克', icon: '🤖' },
];

export function AutoGenerateDialog({
  isOpen,
  onClose,
  characters,
  scenes,
  props = [],
  onGenerate,
  isGenerating,
  progress,
}: AutoGenerateDialogProps) {
  const [selectedModel, setSelectedModel] = useState<string>('');
  const [selectedStyle, setSelectedStyle] = useState<string>('cinematic');
  const [started, setStarted] = useState(false);

  useEffect(() => {
    if (!isOpen) {
      setStarted(false);
      setSelectedModel('');
      setSelectedStyle('cinematic');
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const totalItems = characters.length + scenes.length + props.length;
  const items = [
    ...characters.map(c => ({ type: 'character' as const, name: c.name, description: c.description })),
    ...scenes.map(s => ({ type: 'scene' as const, name: s, description: '' })),
    ...props.map(p => ({ type: 'prop' as const, name: p.name, description: p.description })),
  ];

  const handleStart = async () => {
    if (!selectedModel) return;
    setStarted(true);
    await onGenerate(selectedModel, selectedStyle);
  };

  const handleClose = () => {
    if (!isGenerating) {
      onClose();
    }
  };

  return (
    <div style={{
      position: 'fixed',
      inset: 0,
      backgroundColor: 'var(--overlay-bg)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000,
    }}>
      <div style={{
        backgroundColor: 'var(--bg-secondary)',
        borderRadius: '16px',
        width: '90%',
        maxWidth: '520px',
        maxHeight: '90vh',
        overflow: 'auto',
        border: '1px solid var(--border-primary)',
        boxShadow: 'var(--shadow-lg)',
      }}>
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '20px 24px',
          borderBottom: '1px solid var(--border-primary)',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{
              width: '40px',
              height: '40px',
              borderRadius: '10px',
              background: 'var(--gradient-primary)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}>
              <Sparkles style={{ width: '20px', height: '20px', color: '#fff' }} />
            </div>
            <div>
              <h2 style={{ margin: 0, fontSize: '18px', fontWeight: '600', color: 'var(--text-primary)' }}>
                自动生成
              </h2>
              <p style={{ margin: 0, fontSize: '13px', color: 'var(--text-secondary)' }}>
                从剧本中识别到 {characters.length} 个角色，{scenes.length} 个场景，{props.length} 个物品
              </p>
            </div>
          </div>
          {!isGenerating && (
            <button
              onClick={handleClose}
              style={{
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                padding: '8px',
                borderRadius: '8px',
                color: 'var(--text-secondary)',
              }}
            >
              <X style={{ width: '20px', height: '20px' }} />
            </button>
          )}
        </div>

        <div style={{ padding: '24px' }}>
          {!started ? (
            <>
              <div style={{ marginBottom: '20px' }}>
                <div style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(3, 1fr)',
                  gap: '12px',
                }}>
                  <div style={{
                    padding: '16px',
                    borderRadius: '12px',
                    background: 'var(--bg-hover)',
                    border: '1px solid var(--border-primary)',
                    textAlign: 'center',
                  }}>
                    <Users style={{ width: '24px', height: '24px', color: 'var(--accent)', margin: '0 auto 8px' }} />
                    <div style={{ fontSize: '24px', fontWeight: '700', color: 'var(--text-primary)' }}>
                      {characters.length}
                    </div>
                    <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>角色</div>
                  </div>
                  <div style={{
                    padding: '16px',
                    borderRadius: '12px',
                    background: 'var(--bg-hover)',
                    border: '1px solid var(--border-primary)',
                    textAlign: 'center',
                  }}>
                    <MapPin style={{ width: '24px', height: '24px', color: 'var(--success)', margin: '0 auto 8px' }} />
                    <div style={{ fontSize: '24px', fontWeight: '700', color: 'var(--text-primary)' }}>
                      {scenes.length}
                    </div>
                    <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>场景</div>
                  </div>
                  <div style={{
                    padding: '16px',
                    borderRadius: '12px',
                    background: 'var(--bg-hover)',
                    border: '1px solid var(--border-primary)',
                    textAlign: 'center',
                  }}>
                    <Package style={{ width: '24px', height: '24px', color: 'var(--warning)', margin: '0 auto 8px' }} />
                    <div style={{ fontSize: '24px', fontWeight: '700', color: 'var(--text-primary)' }}>
                      {props.length}
                    </div>
                    <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>物品</div>
                  </div>
                </div>
              </div>

              <div style={{ marginBottom: '20px' }}>
                <label style={{
                  display: 'block',
                  fontSize: '14px',
                  fontWeight: '500',
                  color: 'var(--text-primary)',
                  marginBottom: '8px',
                }}>
                  选择 AI 模型
                </label>
                <ModelSelector
                  contentType="script"
                  value={selectedModel}
                  onChange={setSelectedModel}
                  placeholder="选择 AI 模型"
                  showLastUsed={true}
                  showDefault={true}
                />
              </div>

              <div style={{ marginBottom: '20px' }}>
                <label style={{
                  display: 'block',
                  fontSize: '14px',
                  fontWeight: '500',
                  color: 'var(--text-primary)',
                  marginBottom: '8px',
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <Palette style={{ width: '16px', height: '16px', color: 'var(--accent)' }} />
                    生成风格
                  </div>
                </label>
                <div style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(3, 1fr)',
                  gap: '10px',
                }}>
                  {STYLE_OPTIONS.map((style) => (
                    <button
                      key={style.id}
                      onClick={() => setSelectedStyle(style.id)}
                      disabled={isGenerating}
                      style={{
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'center',
                        gap: '6px',
                        padding: '12px',
                        borderRadius: '10px',
                        border: `2px solid ${selectedStyle === style.id ? 'var(--accent)' : 'var(--border-primary)'}`,
                        backgroundColor: selectedStyle === style.id ? 'var(--accent-bg)' : 'var(--bg-surface)',
                        cursor: 'pointer',
                        transition: 'all 0.2s ease',
                      }}
                      onMouseEnter={(e) => {
                        if (selectedStyle !== style.id) {
                          e.currentTarget.style.backgroundColor = 'var(--bg-hover)';
                          e.currentTarget.style.borderColor = 'var(--accent)';
                        }
                      }}
                      onMouseLeave={(e) => {
                        if (selectedStyle !== style.id) {
                          e.currentTarget.style.backgroundColor = 'var(--bg-surface)';
                          e.currentTarget.style.borderColor = 'var(--border-primary)';
                        }
                      }}
                    >
                      <span style={{ fontSize: '24px' }}>{style.icon}</span>
                      <span style={{
                        fontSize: '13px',
                        fontWeight: selectedStyle === style.id ? '600' : '500',
                        color: selectedStyle === style.id ? 'var(--accent)' : 'var(--text-primary)',
                      }}>
                        {style.name}
                      </span>
                    </button>
                  ))}
                </div>
              </div>

              <div style={{
                padding: '12px 16px',
                background: 'var(--accent-bg)',
                borderRadius: '8px',
                marginBottom: '24px',
              }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
                  <AlertCircle style={{ width: '18px', height: '18px', color: 'var(--accent)', flexShrink: 0, marginTop: '2px' }} />
                  <div style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: '1.5' }}>
                    将使用 AI 自动生成角色图片、物品图片和场景图片。生成过程中如遇失败将跳过并继续。
                  </div>
                </div>
              </div>

              <div style={{ display: 'flex', gap: '12px' }}>
                <Button
                  variant="outline"
                  onClick={onClose}
                  style={{ flex: 1 }}
                  disabled={isGenerating}
                >
                  取消
                </Button>
                <Button
                  onClick={handleStart}
                  disabled={!selectedModel || !selectedStyle}
                  style={{ flex: 1, background: 'var(--gradient-primary)' }}
                >
                  开始生成
                  <ArrowRight style={{ width: '16px', height: '16px', marginLeft: '8px' }} />
                </Button>
              </div>
            </>
          ) : (
            <>
              <div style={{ marginBottom: '24px' }}>
                <div style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  marginBottom: '8px',
                }}>
                  <span style={{ fontSize: '14px', color: 'var(--text-secondary)' }}>
                    进度
                  </span>
                  <span style={{ fontSize: '14px', color: 'var(--text-primary)', fontWeight: '500' }}>
                    {progress.current} / {progress.total}
                  </span>
                </div>
                <div style={{
                  height: '8px',
                  background: 'var(--bg-hover)',
                  borderRadius: '4px',
                  overflow: 'hidden',
                }}>
                  <div style={{
                    height: '100%',
                    width: `${progress.total > 0 ? (progress.current / progress.total) * 100 : 0}%`,
                    background: 'var(--gradient-primary)',
                    borderRadius: '4px',
                    transition: 'width 0.3s ease',
                  }} />
                </div>
                <div style={{
                  marginTop: '12px',
                  fontSize: '13px',
                  color: 'var(--text-secondary)',
                  textAlign: 'center',
                }}>
                  {progress.status || '正在生成...'}
                </div>
              </div>

              <div style={{
                maxHeight: '200px',
                overflow: 'auto',
                border: '1px solid var(--border-primary)',
                borderRadius: '8px',
              }}>
                {items.map((item, index) => (
                  <div
                    key={index}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '12px',
                      padding: '10px 14px',
                      borderBottom: index < items.length - 1 ? '1px solid var(--border-primary)' : 'none',
                      background: index < progress.current ? 'var(--success-bg)' : 'transparent',
                    }}
                  >
                    {index < progress.current ? (
                      <Check style={{ width: '16px', height: '16px', color: 'var(--success)' }} />
                    ) : isGenerating ? (
                      <Loader2 style={{ width: '16px', height: '16px', color: 'var(--text-muted)', animation: 'spin 1s linear infinite' }} />
                    ) : (
                      <div style={{ width: '16px', height: '16px' }} />
                    )}
                    {item.type === 'character' && <Users style={{ width: '14px', height: '14px', color: 'var(--accent)' }} />}
                    {item.type === 'scene' && <MapPin style={{ width: '14px', height: '14px', color: 'var(--success)' }} />}
                    {item.type === 'prop' && <Package style={{ width: '14px', height: '14px', color: 'var(--warning)' }} />}
                    <span style={{
                      fontSize: '13px',
                      color: index < progress.current ? 'var(--success)' : 'var(--text-primary)',
                      flex: 1,
                    }}>
                      {item.name}
                    </span>
                  </div>
                ))}
              </div>

              {!isGenerating && (
                <Button
                  onClick={onClose}
                  style={{ width: '100%', marginTop: '20px' }}
                >
                  完成
                </Button>
              )}
            </>
          )}
        </div>

        <style>{`
          @keyframes spin {
            from { transform: rotate(0deg); }
            to { transform: rotate(360deg); }
          }
        `}</style>
      </div>
    </div>
  );
}
